spring:
  datasource:
    url: jdbc:mysql://market-mysql-db:3306/marketdb?autoReconnect=true
    username: sa
    password: root
  jpa:
    show-sql: true
    hibernate:  
      ddl-auto: update  
  activemq:
    broker-url: tcp://activemq:9876
    user: admin
    url: tcp://activemq:61616
    password: admin

server:
  port: 8081
  error:
    whitelabel:
      enabled: false

