spring:
  datasource:
    url: jdbc:mysql://localhost:3306/marketdb?useSSL=false&serverTimezone=Europe/Moscow&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  activemq:
    broker-url: tcp://192.168.1.210:9876
    user: admin
    url: tcp://localhost:61616
    password: admin

server:
  port: 8081
  error:
    whitelabel:
      enabled: false

