spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketdb
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  activemq:
    broker-url: tcp://localhost:9876
    user: admin
    url: tcp://localhost:61616
    password: admin

server:
  port: 8081
  error:
    whitelabel:
      enabled: false
