version: '3.6'
services:

  mysql-container:
    container_name: market-mysql-standalone
    image: mysql
    environment:
      MYSQL_DATABASE: marketdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sa
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d


  spring-boot-docker-container:
    image: spring-boot-docker-container
    command: mvn clean spring-boot:run
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - mysql-container